// P8.2 - embedded copy of artifacts/v0/P7_1_PLATFORM_KPI_CROSSWALK.csv
// (the locked P7.1 baseline). Workers have no filesystem access at runtime,
// so this is generated once from the CSV and imported directly.
// Regenerate with the same csv->json conversion if the CSV is ever updated.

export interface CrosswalkRow {
  HH_KPI: string;
  PLATFORM: string;
  SECTION: string;
  OFFICIAL_ENDPOINT: string;
  API_FIELD: string;
  FORMULA_IF_DERIVED: string;
  GRAIN: string;
  CURRENT_PERMISSION: string;
  REAL_PAYLOAD_PROVEN: string;
  CORE_LOCATION: string;
  MART_LOCATION: string;
  AI_VIEW: string;
  STATUS: string;
  GAP_ACTION: string;
}

export const CROSSWALK: CrosswalkRow[] = [
  {
    "HH_KPI": "(no KPI rows defined in source sheet for this section)",
    "PLATFORM": "SHOPEE",
    "SECTION": "AFF Video Shopee",
    "OFFICIAL_ENDPOINT": "N/A",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "N/A",
    "GRAIN": "N/A",
    "CURRENT_PERMISSION": "N/A",
    "REAL_PAYLOAD_PROVEN": "N/A",
    "CORE_LOCATION": "N/A",
    "MART_LOCATION": "N/A",
    "AI_VIEW": "N/A",
    "STATUS": "EMPTY_IN_SOURCE",
    "GAP_ACTION": "Source sheet defines zero KPI rows here. Bonus finding: Shopee AMS get_content_performance(channel=ShopeeVideo/LiveStreaming) IS API_ACTUAL and fully backfilled 2026-09-01..2026-09-12 into core.fact_shopee_affiliate_content_daily (193 real rows total) — available if HH wants to populate this section."
  },
  {
    "HH_KPI": "GMV - Tổng doanh thu gộp video",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Video Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202605/shop_videos/performance",
    "API_FIELD": "gmv.amount",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "video_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED (data.shop_analytics.public.read)",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_tiktok_video_daily.gmv_amount",
    "MART_LOCATION": "mart.v_ai_video_daily",
    "AI_VIEW": "v_ai_video_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Fully backfilled 2026-09-01..2026-09-12, ALL + AFFILIATE_ACCOUNTS (21899 rows total: 11202 ALL + 10697 AFFILIATE_ACCOUNTS), idempotency-proven."
  },
  {
    "HH_KPI": "Đơn hàng SKU - Số đơn hàng trong từng SKU",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Video Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202605/shop_videos/performance",
    "API_FIELD": "sku_orders",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "video_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_tiktok_video_daily.sku_orders",
    "MART_LOCATION": "mart.v_ai_video_daily",
    "AI_VIEW": "v_ai_video_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested."
  },
  {
    "HH_KPI": "Số món bán ra - Tổng số lượng sản phẩm bán được",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Video Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202605/shop_videos/performance",
    "API_FIELD": "items_sold",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "video_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_tiktok_video_daily.items_sold",
    "MART_LOCATION": "mart.v_ai_video_daily",
    "AI_VIEW": "v_ai_video_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested."
  },
  {
    "HH_KPI": "VV (Video Views)",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Video Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202605/shop_videos/performance",
    "API_FIELD": "views",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "video_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_tiktok_video_daily.views",
    "MART_LOCATION": "mart.v_ai_video_daily",
    "AI_VIEW": "v_ai_video_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested."
  },
  {
    "HH_KPI": "Lượt hiển thị sản phẩm - Số lần sản phẩm được hiển thị cho người dùng",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Video Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202605/shop_videos/performance",
    "API_FIELD": "(absent at video grain)",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "video_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "NO (field confirmed absent from the per-video payload — full field dump captured)",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "MISSING_SOURCE",
    "GAP_ACTION": "product_impressions/product_clicks only exist at the shop-daily OVERVIEW grain (video_overview_analytics), not per-video. Grain mismatch, not a permission gap — flagged, not fabricated."
  },
  {
    "HH_KPI": "Lượt nhấp sản phẩm (raw click count)",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Video Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202605/shop_videos/performance",
    "API_FIELD": "(absent at video grain)",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "video_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "MISSING_SOURCE",
    "GAP_ACTION": "Same grain-mismatch reason as product impressions above."
  },
  {
    "HH_KPI": "CTR (Lượt nhấp sản phẩm)",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Video Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202605/shop_videos/performance",
    "API_FIELD": "click_through_rate",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "video_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_tiktok_video_daily.click_through_rate",
    "MART_LOCATION": "mart.v_ai_video_daily",
    "AI_VIEW": "v_ai_video_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested (0.0..1.0 fraction)."
  },
  {
    "HH_KPI": "CTOR - Tỷ lệ click mua hàng",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Video Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202605/shop_videos/performance",
    "API_FIELD": "(absent at video grain; product_clicks missing so sku_orders/product_clicks cannot be derived either)",
    "FORMULA_IF_DERIVED": "sku_orders / product_clicks (rejected — denominator not available at this grain)",
    "GRAIN": "video_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "MISSING_SOURCE",
    "GAP_ACTION": "Proven API_ACTUAL instead at PRODUCT grain via /analytics/202605/shop_products/performance's click_order_rate / shop_tab_performance.shop_tab_ctor_sku fields (different grain — see product_analytics probe evidence). Not substituted here since HH's row is specifically per-video."
  },
  {
    "HH_KPI": "GMV (Tổng giá trị hàng hóa – LIVE)",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Livestream Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202509/shop_lives/performance (account_type=AFFILIATE_ACCOUNTS)",
    "API_FIELD": "sales_performance.gmv.amount",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_live_daily.gmv_amount (account_type='AFFILIATE_ACCOUNTS')",
    "MART_LOCATION": "mart.v_ai_live_daily",
    "AI_VIEW": "v_ai_live_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested — 21 real AFFILIATE_ACCOUNTS LIVE sessions for 2026-09-09 (of 25 total ALL sessions)."
  },
  {
    "HH_KPI": "CTOR (Tỷ lệ nhấp → đặt hàng)",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Livestream Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202509/shop_lives/performance (AFFILIATE_ACCOUNTS)",
    "API_FIELD": "sales_performance.click_to_order_rate",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (math verified: 16/157=10.19% exact match)",
    "CORE_LOCATION": "core.fact_live_daily.click_to_order_rate",
    "MART_LOCATION": "mart.v_ai_live_daily",
    "AI_VIEW": "v_ai_live_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested; confirmed = created_sku_orders/product_clicks matching HH's stated definition exactly."
  },
  {
    "HH_KPI": "Lượt xem (Tổng số người đã vào live)",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Livestream Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202509/shop_lives/performance (AFFILIATE_ACCOUNTS)",
    "API_FIELD": "interaction_performance.views",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_live_daily.views",
    "MART_LOCATION": "mart.v_ai_live_daily",
    "AI_VIEW": "v_ai_live_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested."
  },
  {
    "HH_KPI": "Thời gian live",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Livestream Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202509/shop_lives/performance (AFFILIATE_ACCOUNTS)",
    "API_FIELD": "start_time / end_time",
    "FORMULA_IF_DERIVED": "end_time - start_time (seconds)",
    "GRAIN": "live_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (both inputs API_ACTUAL; subtraction is unambiguous)",
    "CORE_LOCATION": "core.fact_live_daily.duration_seconds",
    "MART_LOCATION": "mart.v_ai_live_daily",
    "AI_VIEW": "v_ai_live_daily",
    "STATUS": "DERIVED_VERIFIED",
    "GAP_ACTION": "Ingested."
  },
  {
    "HH_KPI": "Lượt hiện thị sản phẩm",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Livestream Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202509/shop_lives/performance (AFFILIATE_ACCOUNTS)",
    "API_FIELD": "interaction_performance.product_impressions",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_live_daily.product_impressions",
    "MART_LOCATION": "mart.v_ai_live_daily",
    "AI_VIEW": "v_ai_live_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested. Note this IS product-level impressions, matching HH's own label — distinct from the room-level \"Lượt hiển thị\" concept in the general LIVE TIKTOK section below."
  },
  {
    "HH_KPI": "CTR",
    "PLATFORM": "TIKTOK",
    "SECTION": "AFF Livestream Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202509/shop_lives/performance (AFFILIATE_ACCOUNTS)",
    "API_FIELD": "interaction_performance.click_through_rate",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (math verified: 157/2539=6.18% exact match against product_impressions — NOT views)",
    "CORE_LOCATION": "core.fact_live_daily.click_through_rate",
    "MART_LOCATION": "mart.v_ai_live_daily",
    "AI_VIEW": "v_ai_live_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested. CAVEAT: HH's own Vietnamese definition text says \"chia lượt xem\" (divide by views) but the proven real denominator is product_impressions. Field is still API_ACTUAL (a direct TikTok field), documented discrepancy for HH awareness, not corrected/overridden."
  },
  {
    "HH_KPI": "Tỉ lệ chuyển đổi >=3% (viewer-to-order rate)",
    "PLATFORM": "SHOPEE",
    "SECTION": "LIVE Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/livestream/get_session_metric",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "orders / views (task-specified formula — untestable)",
    "GRAIN": "session_id",
    "CURRENT_PERMISSION": "BLOCKED",
    "REAL_PAYLOAD_PROVEN": "NO (endpoint unreachable — see probe evidence)",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NO_PERMISSION",
    "GAP_ACTION": "Shopee Livestream API requires a numeric 'user_id' our Partner/shop token cannot supply (confirmed via 3 distinct live error responses: 'no user_id in query' -> valid-range check on user_id=0 -> 'Wrong sign' once user_id is supplied, meaning a DIFFERENT signing/auth scheme is required). This is a separate Shopee Live Open Platform enrollment gap, not a fixable parameter bug."
  },
  {
    "HH_KPI": "Thời gian xem Trung bình >=1p",
    "PLATFORM": "SHOPEE",
    "SECTION": "LIVE Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/livestream/get_session_metric",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "session_id",
    "CURRENT_PERMISSION": "BLOCKED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NO_PERMISSION",
    "GAP_ACTION": "Same root cause as above."
  },
  {
    "HH_KPI": "Lượt xem",
    "PLATFORM": "SHOPEE",
    "SECTION": "LIVE Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/livestream/get_session_metric",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "session_id",
    "CURRENT_PERMISSION": "BLOCKED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NO_PERMISSION",
    "GAP_ACTION": "Same root cause as above."
  },
  {
    "HH_KPI": "Lượt thích",
    "PLATFORM": "SHOPEE",
    "SECTION": "LIVE Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/livestream/get_session_metric",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "session_id",
    "CURRENT_PERMISSION": "BLOCKED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NO_PERMISSION",
    "GAP_ACTION": "Same root cause as above."
  },
  {
    "HH_KPI": "Lượt nhấp sản phẩm",
    "PLATFORM": "SHOPEE",
    "SECTION": "LIVE Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/livestream/get_session_item_metric",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "session_id + item_id",
    "CURRENT_PERMISSION": "BLOCKED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NO_PERMISSION",
    "GAP_ACTION": "Same root cause as above."
  },
  {
    "HH_KPI": "Lượt chia sẻ",
    "PLATFORM": "SHOPEE",
    "SECTION": "LIVE Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/livestream/get_session_metric",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "session_id",
    "CURRENT_PERMISSION": "BLOCKED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NO_PERMISSION",
    "GAP_ACTION": "Same root cause as above."
  },
  {
    "HH_KPI": "Bình luận",
    "PLATFORM": "SHOPEE",
    "SECTION": "LIVE Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/livestream/get_session_metric",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "session_id",
    "CURRENT_PERMISSION": "BLOCKED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NO_PERMISSION",
    "GAP_ACTION": "Same root cause as above."
  },
  {
    "HH_KPI": "Voucher hiển thị",
    "PLATFORM": "SHOPEE",
    "SECTION": "LIVE Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/livestream/get_session_metric",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "session_id",
    "CURRENT_PERMISSION": "BLOCKED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NO_PERMISSION",
    "GAP_ACTION": "Blocked by the same auth gap; additionally, per Section 10, this field's existence in get_session_metric's documented response has not been confirmed even in principle — do not assume."
  },
  {
    "HH_KPI": "Voucher đã dùng",
    "PLATFORM": "SHOPEE",
    "SECTION": "LIVE Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/livestream/get_session_metric",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "session_id",
    "CURRENT_PERMISSION": "BLOCKED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NO_PERMISSION",
    "GAP_ACTION": "Same caveat as Voucher hiển thị."
  },
  {
    "HH_KPI": "Doanh số trên mỗi Người mua",
    "PLATFORM": "SHOPEE",
    "SECTION": "LIVE Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/livestream/get_session_metric",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "gmv / customers (task-specified formula — untestable)",
    "GRAIN": "session_id",
    "CURRENT_PERMISSION": "BLOCKED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NO_PERMISSION",
    "GAP_ACTION": "Same root cause as above."
  },
  {
    "HH_KPI": "Lượt hiển thị (room distribution, pre-click)",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202510/shop_lives/{live_id}/performance_per_minutes",
    "API_FIELD": "traffic.impressions",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + interval_start",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (confirmed a DISTINCT field from product_impressions in the same payload)",
    "CORE_LOCATION": "core.fact_tiktok_live_minute.room_impressions",
    "MART_LOCATION": "mart.v_ai_live_minute_daily",
    "AI_VIEW": "v_ai_live_minute_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested: 4/25 live_ids (own-account only, see EXC-013)."
  },
  {
    "HH_KPI": "Lượt xem",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202510/shop_lives/{live_id}/performance_per_minutes",
    "API_FIELD": "traffic.views",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + interval_start",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_tiktok_live_minute.views",
    "MART_LOCATION": "mart.v_ai_live_minute_daily",
    "AI_VIEW": "v_ai_live_minute_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested (all 12 dates). REAL PERMISSION BOUNDARY DISCOVERED during ingestion (2026-09-09, 25 known live_ids): this live_id-scoped endpoint only returns real data for HH's OWN account (lepetitmarseillaisvn, 4/25 sessions) — for affiliate-creator-hosted LIVE sessions it returns Permission Denied (performance_per_minutes) or an empty result (products_performance), even though the session-summary endpoint (shop_lives/performance) DOES cover affiliate sessions. Ingested successfully for the 4 own-account sessions; affiliate-hosted sessions at this specific grain are a genuine coverage gap, not a bug. Full backfill 2026-09-01..2026-09-12 completed and idempotency-proven (0 new rows on rerun, 0 duplicates)."
  },
  {
    "HH_KPI": "GMV/giờ",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "(derived from live_analytics)",
    "API_FIELD": "gmv_amount / (duration_seconds/3600.0)",
    "FORMULA_IF_DERIVED": "live_gmv / live_duration_hours",
    "GRAIN": "live_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (both inputs API_ACTUAL and already stored)",
    "CORE_LOCATION": "core.fact_live_daily (inputs: gmv_amount, duration_seconds)",
    "MART_LOCATION": "mart.v_ai_live_daily (computed column)",
    "AI_VIEW": "v_ai_live_daily",
    "STATUS": "DERIVED_VERIFIED",
    "GAP_ACTION": "Computed at query time in the mart view — not stored as a redundant raw column."
  },
  {
    "HH_KPI": "Lượt hiển thị mỗi giờ",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "(derived from live_performance_per_minutes rollup)",
    "API_FIELD": "SUM(room_impressions) / (duration_seconds/3600.0)",
    "FORMULA_IF_DERIVED": "sum of per-minute room_impressions for the live / live_duration_hours",
    "GRAIN": "live_id + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (room_impressions proven API_ACTUAL per-minute; rollup is a plain SUM)",
    "CORE_LOCATION": "core.fact_tiktok_live_minute (input, fully backfilled)",
    "MART_LOCATION": "mart.v_ai_live_minute_daily (base view live; per-live rollup still not built)",
    "AI_VIEW": "v_ai_live_minute_daily (base only)",
    "STATUS": "DERIVED_VERIFIED",
    "GAP_ACTION": "Requires a mart-layer rollup of fact_tiktok_live_minute by live_id before dividing by duration — not yet built this pass; formula and inputs proven. REAL PERMISSION BOUNDARY DISCOVERED during ingestion (2026-09-09, 25 known live_ids): this live_id-scoped endpoint only returns real data for HH's OWN account (lepetitmarseillaisvn, 4/25 sessions) — for affiliate-creator-hosted LIVE sessions it returns Permission Denied (performance_per_minutes) or an empty result (products_performance), even though the session-summary endpoint (shop_lives/performance) DOES cover affiliate sessions. Ingested successfully for the 4 own-account sessions; affiliate-hosted sessions at this specific grain are a genuine coverage gap, not a bug. Full backfill 2026-09-01..2026-09-12 completed and idempotency-proven (0 new rows on rerun, 0 duplicates)."
  },
  {
    "HH_KPI": "GPM hiển thị",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202510/shop_lives/{live_id}/performance_per_minutes",
    "API_FIELD": "conversion.gpm.show_gpm",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + interval_start",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (TikTok computes this metric itself — not our formula)",
    "CORE_LOCATION": "core.fact_tiktok_live_minute.show_gpm",
    "MART_LOCATION": "mart.v_ai_live_minute_daily",
    "AI_VIEW": "v_ai_live_minute_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested (all 12 dates). REAL PERMISSION BOUNDARY DISCOVERED during ingestion (2026-09-09, 25 known live_ids): this live_id-scoped endpoint only returns real data for HH's OWN account (lepetitmarseillaisvn, 4/25 sessions) — for affiliate-creator-hosted LIVE sessions it returns Permission Denied (performance_per_minutes) or an empty result (products_performance), even though the session-summary endpoint (shop_lives/performance) DOES cover affiliate sessions. Ingested successfully for the 4 own-account sessions; affiliate-hosted sessions at this specific grain are a genuine coverage gap, not a bug. Full backfill 2026-09-01..2026-09-12 completed and idempotency-proven (0 new rows on rerun, 0 duplicates)."
  },
  {
    "HH_KPI": "Thời lượng xem trung bình mỗi lượt xem",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202509/shop_lives/performance",
    "API_FIELD": "interaction_performance.avg_viewing_duration",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + account_type + business_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_live_daily.avg_viewing_duration_secs",
    "MART_LOCATION": "mart.v_ai_live_daily",
    "AI_VIEW": "v_ai_live_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested."
  },
  {
    "HH_KPI": "Tỷ lệ bình luận",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202510/shop_lives/{live_id}/performance_per_minutes",
    "API_FIELD": "interactions.comment_rate",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + interval_start",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (TikTok returns this rate directly — not derived by us)",
    "CORE_LOCATION": "core.fact_tiktok_live_minute.comment_rate",
    "MART_LOCATION": "mart.v_ai_live_minute_daily",
    "AI_VIEW": "v_ai_live_minute_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested (all 12 dates). REAL PERMISSION BOUNDARY DISCOVERED during ingestion (2026-09-09, 25 known live_ids): this live_id-scoped endpoint only returns real data for HH's OWN account (lepetitmarseillaisvn, 4/25 sessions) — for affiliate-creator-hosted LIVE sessions it returns Permission Denied (performance_per_minutes) or an empty result (products_performance), even though the session-summary endpoint (shop_lives/performance) DOES cover affiliate sessions. Ingested successfully for the 4 own-account sessions; affiliate-hosted sessions at this specific grain are a genuine coverage gap, not a bug. Full backfill 2026-09-01..2026-09-12 completed and idempotency-proven (0 new rows on rerun, 0 duplicates)."
  },
  {
    "HH_KPI": "Tỷ lệ theo dõi",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202510/shop_lives/{live_id}/performance_per_minutes",
    "API_FIELD": "interactions.follow_rate",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + interval_start",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_tiktok_live_minute.follow_rate",
    "MART_LOCATION": "mart.v_ai_live_minute_daily",
    "AI_VIEW": "v_ai_live_minute_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested (all 12 dates). REAL PERMISSION BOUNDARY DISCOVERED during ingestion (2026-09-09, 25 known live_ids): this live_id-scoped endpoint only returns real data for HH's OWN account (lepetitmarseillaisvn, 4/25 sessions) — for affiliate-creator-hosted LIVE sessions it returns Permission Denied (performance_per_minutes) or an empty result (products_performance), even though the session-summary endpoint (shop_lives/performance) DOES cover affiliate sessions. Ingested successfully for the 4 own-account sessions; affiliate-hosted sessions at this specific grain are a genuine coverage gap, not a bug. Full backfill 2026-09-01..2026-09-12 completed and idempotency-proven (0 new rows on rerun, 0 duplicates)."
  },
  {
    "HH_KPI": "Tỷ lệ vào phòng (qua bản xem trước buổi LIVE)",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202510/shop_lives/{live_id}/performance_per_minutes",
    "API_FIELD": "(no distinct preview-specific field found)",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + interval_start",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "NO (only one generic enter_room_rate field exists in the payload — no separate preview-specific variant)",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NOT_EXPOSED_PUBLIC_API",
    "GAP_ACTION": "Only a single generic enter_room_rate field was found; cannot confirm a preview-specific breakdown exists. Not substituted with the generic field to avoid conflating two distinct HH-defined KPIs."
  },
  {
    "HH_KPI": "Tỷ lệ vào phòng",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202510/shop_lives/{live_id}/performance_per_minutes",
    "API_FIELD": "traffic.enter_room_rate",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + interval_start",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_tiktok_live_minute.enter_room_rate",
    "MART_LOCATION": "mart.v_ai_live_minute_daily",
    "AI_VIEW": "v_ai_live_minute_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested (all 12 dates). Mapped to the generic (non-preview) room-entry rate. REAL PERMISSION BOUNDARY DISCOVERED during ingestion (2026-09-09, 25 known live_ids): this live_id-scoped endpoint only returns real data for HH's OWN account (lepetitmarseillaisvn, 4/25 sessions) — for affiliate-creator-hosted LIVE sessions it returns Permission Denied (performance_per_minutes) or an empty result (products_performance), even though the session-summary endpoint (shop_lives/performance) DOES cover affiliate sessions. Ingested successfully for the 4 own-account sessions; affiliate-hosted sessions at this specific grain are a genuine coverage gap, not a bug. Full backfill 2026-09-01..2026-09-12 completed and idempotency-proven (0 new rows on rerun, 0 duplicates)."
  },
  {
    "HH_KPI": "Tỷ lệ nhấp",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202510/shop_lives/{live_id}/performance_per_minutes",
    "API_FIELD": "traffic.ctr",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + interval_start",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_tiktok_live_minute.ctr",
    "MART_LOCATION": "mart.v_ai_live_minute_daily",
    "AI_VIEW": "v_ai_live_minute_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested (all 12 dates). REAL PERMISSION BOUNDARY DISCOVERED during ingestion (2026-09-09, 25 known live_ids): this live_id-scoped endpoint only returns real data for HH's OWN account (lepetitmarseillaisvn, 4/25 sessions) — for affiliate-creator-hosted LIVE sessions it returns Permission Denied (performance_per_minutes) or an empty result (products_performance), even though the session-summary endpoint (shop_lives/performance) DOES cover affiliate sessions. Ingested successfully for the 4 own-account sessions; affiliate-hosted sessions at this specific grain are a genuine coverage gap, not a bug. Full backfill 2026-09-01..2026-09-12 completed and idempotency-proven (0 new rows on rerun, 0 duplicates)."
  },
  {
    "HH_KPI": "Tỷ lệ đặt hàng (đơn hàng SKU)",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202510/shop_lives/{live_id}/performance_per_minutes",
    "API_FIELD": "conversion.sku_order_rate",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + interval_start",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_tiktok_live_minute (add sku_order_rate — see exceptions)",
    "MART_LOCATION": "mart.v_ai_live_minute_daily",
    "AI_VIEW": "v_ai_live_minute_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Field confirmed real in probe payload; not yet added as a stored column in this pass's schema (fact_tiktok_live_minute has sku_orders count but not this specific rate field) — see P7_1_KPI_EXCEPTIONS.csv. REAL PERMISSION BOUNDARY DISCOVERED during ingestion (2026-09-09, 25 known live_ids): this live_id-scoped endpoint only returns real data for HH's OWN account (lepetitmarseillaisvn, 4/25 sessions) — for affiliate-creator-hosted LIVE sessions it returns Permission Denied (performance_per_minutes) or an empty result (products_performance), even though the session-summary endpoint (shop_lives/performance) DOES cover affiliate sessions. Ingested successfully for the 4 own-account sessions; affiliate-hosted sessions at this specific grain are a genuine coverage gap, not a bug."
  },
  {
    "HH_KPI": "Tỷ lệ chia sẻ",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202510/shop_lives/{live_id}/performance_per_minutes",
    "API_FIELD": "interactions.share_rate",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + interval_start",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_tiktok_live_minute.share_rate",
    "MART_LOCATION": "mart.v_ai_live_minute_daily",
    "AI_VIEW": "v_ai_live_minute_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested (all 12 dates). REAL PERMISSION BOUNDARY DISCOVERED during ingestion (2026-09-09, 25 known live_ids): this live_id-scoped endpoint only returns real data for HH's OWN account (lepetitmarseillaisvn, 4/25 sessions) — for affiliate-creator-hosted LIVE sessions it returns Permission Denied (performance_per_minutes) or an empty result (products_performance), even though the session-summary endpoint (shop_lives/performance) DOES cover affiliate sessions. Ingested successfully for the 4 own-account sessions; affiliate-hosted sessions at this specific grain are a genuine coverage gap, not a bug. Full backfill 2026-09-01..2026-09-12 completed and idempotency-proven (0 new rows on rerun, 0 duplicates)."
  },
  {
    "HH_KPI": "Tỷ lệ thích",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "GET /analytics/202510/shop_lives/{live_id}/performance_per_minutes",
    "API_FIELD": "interactions.like_rate",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id + interval_start",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES",
    "CORE_LOCATION": "core.fact_tiktok_live_minute.like_rate",
    "MART_LOCATION": "mart.v_ai_live_minute_daily",
    "AI_VIEW": "v_ai_live_minute_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested (all 12 dates). REAL PERMISSION BOUNDARY DISCOVERED during ingestion (2026-09-09, 25 known live_ids): this live_id-scoped endpoint only returns real data for HH's OWN account (lepetitmarseillaisvn, 4/25 sessions) — for affiliate-creator-hosted LIVE sessions it returns Permission Denied (performance_per_minutes) or an empty result (products_performance), even though the session-summary endpoint (shop_lives/performance) DOES cover affiliate sessions. Ingested successfully for the 4 own-account sessions; affiliate-hosted sessions at this specific grain are a genuine coverage gap, not a bug. Full backfill 2026-09-01..2026-09-12 completed and idempotency-proven (0 new rows on rerun, 0 duplicates)."
  },
  {
    "HH_KPI": "Lượt xem > 1 phút",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "(none found)",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "live_id",
    "CURRENT_PERMISSION": "GRANTED (scope) but field absent",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NOT_EXPOSED_PUBLIC_API",
    "GAP_ACTION": "No per-viewer duration-threshold/histogram field found in any probed endpoint. Left NULL/manual per task instruction — not derived from avg_viewing_duration (would be a fabrication of a materially different metric)."
  },
  {
    "HH_KPI": "Chi phí quảng cáo",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok",
    "OFFICIAL_ENDPOINT": "TikTok API for Business /report/integrated/get/",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "campaign",
    "CURRENT_PERMISSION": "BLOCKED (Ads Developer Profile pending approval)",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "SEPARATE_API_REQUIRED",
    "GAP_ACTION": "TIKTOK_ADS_STATUS = BLOCKED_BY_DEVELOPER_PROFILE. Not substituted with Shop Analytics data per explicit instruction."
  },
  {
    "HH_KPI": "Business thresholds/targets (AFF revenue share ≥55%, KOC active ≥20, AFF cost/revenue ≤4%, videos/KOC per month, room-entry ≥2.5%, retention ≥45s, CR≥2%)",
    "PLATFORM": "TIKTOK",
    "SECTION": "LIVE Tiktok (reference row)",
    "OFFICIAL_ENDPOINT": "N/A",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "N/A",
    "GRAIN": "N/A",
    "CURRENT_PERMISSION": "N/A",
    "REAL_PAYLOAD_PROVEN": "N/A",
    "CORE_LOCATION": "N/A",
    "MART_LOCATION": "N/A",
    "AI_VIEW": "N/A",
    "STATUS": "TARGET_THRESHOLD_NOT_A_KPI",
    "GAP_ACTION": "Not a data KPI — a set of business targets to compare already-ingested KPIs against in a dashboard/reporting layer. No ingestion needed."
  },
  {
    "HH_KPI": "Tỷ lệ đơn hàng không thành công",
    "PLATFORM": "SHOPEE",
    "SECTION": "VẬN HÀNH Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/account_health/get_shop_performance",
    "API_FIELD": "metric_list[metric_id=3].current_period (non_fulfillment_rate)",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "snapshot_date + metric_id",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (current_period=0 for this shop today)",
    "CORE_LOCATION": "core.fact_shopee_account_health_snapshot",
    "MART_LOCATION": "mart.v_ai_operations_daily",
    "AI_VIEW": "v_ai_operations_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Mapped via Shopee's own definition text match (cancel+return due to seller fault / total orders), which is materially identical to HH's Vietnamese definition."
  },
  {
    "HH_KPI": "Tỷ lệ giao hàng trễ",
    "PLATFORM": "SHOPEE",
    "SECTION": "VẬN HÀNH Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/account_health/get_shop_performance",
    "API_FIELD": "metric_list[metric_id=1].current_period (late_shipment_rate)",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "snapshot_date + metric_id",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (current_period=0.09)",
    "CORE_LOCATION": "core.fact_shopee_account_health_snapshot",
    "MART_LOCATION": "mart.v_ai_operations_daily",
    "AI_VIEW": "v_ai_operations_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested."
  },
  {
    "HH_KPI": "Thời gian chuẩn bị hàng",
    "PLATFORM": "SHOPEE",
    "SECTION": "VẬN HÀNH Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/account_health/get_shop_performance",
    "API_FIELD": "metric_list[metric_id=4].current_period (preparation_time)",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "snapshot_date + metric_id",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (current_period=0.51)",
    "CORE_LOCATION": "core.fact_shopee_account_health_snapshot",
    "MART_LOCATION": "mart.v_ai_operations_daily",
    "AI_VIEW": "v_ai_operations_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested."
  },
  {
    "HH_KPI": "Thời gian / tỷ lệ phản hồi chat",
    "PLATFORM": "SHOPEE",
    "SECTION": "VẬN HÀNH Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/account_health/get_shop_performance",
    "API_FIELD": "metric_list[metric_id=11] returned as response_rate (%); metric_id=29 average_response_time (task's expected TIME variant) NOT returned for this shop",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "snapshot_date + metric_id",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "PARTIAL (rate=YES; time=NO — confirmed absent from this shop's real metric_list of 15 metrics)",
    "CORE_LOCATION": "core.fact_shopee_account_health_snapshot (metric_id=11 only)",
    "MART_LOCATION": "mart.v_ai_operations_daily",
    "AI_VIEW": "v_ai_operations_daily",
    "STATUS": "MISSING_SOURCE",
    "GAP_ACTION": "HH's KPI literally asks for response TIME; only response RATE (metric_id=11) is returned for this shop currently. Not substituted — rate ingested as its own real metric, time left genuinely missing."
  },
  {
    "HH_KPI": "Đánh giá Shop",
    "PLATFORM": "SHOPEE",
    "SECTION": "VẬN HÀNH Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/account_health/get_shop_performance",
    "API_FIELD": "metric_list[metric_id=22].current_period (shop_rating) + overall_performance.rating",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "snapshot_date + metric_id",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (current_period=4.91; overall_performance.rating=4)",
    "CORE_LOCATION": "core.fact_shopee_account_health_snapshot",
    "MART_LOCATION": "mart.v_ai_operations_daily",
    "AI_VIEW": "v_ai_operations_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested (both the granular metric and the coarse overall rating captured)."
  },
  {
    "HH_KPI": "Sản phẩm bị khóa/xóa / listing violations",
    "PLATFORM": "SHOPEE",
    "SECTION": "VẬN HÀNH Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/account_health/get_shop_performance",
    "API_FIELD": "metric_list[metric_id=52].current_period (severe_listing_violations)",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "snapshot_date + metric_id",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (current_period=NULL — real; no violations this period; not fabricated 0)",
    "CORE_LOCATION": "core.fact_shopee_account_health_snapshot",
    "MART_LOCATION": "mart.v_ai_operations_daily",
    "AI_VIEW": "v_ai_operations_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested; also see get_listings_with_issues (PASS_EMPTY, 0 rows, real)."
  },
  {
    "HH_KPI": "Các vi phạm khác",
    "PLATFORM": "SHOPEE",
    "SECTION": "VẬN HÀNH Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/account_health/get_shop_performance",
    "API_FIELD": "metric_list[metric_id=53].current_period (other_listing_violations)",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "snapshot_date + metric_id",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (current_period=NULL — real)",
    "CORE_LOCATION": "core.fact_shopee_account_health_snapshot",
    "MART_LOCATION": "mart.v_ai_operations_daily",
    "AI_VIEW": "v_ai_operations_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Ingested."
  },
  {
    "HH_KPI": "Tỷ Lệ Giao Hàng Nhanh",
    "PLATFORM": "SHOPEE",
    "SECTION": "VẬN HÀNH Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/account_health/get_shop_performance",
    "API_FIELD": "metric_id=25 (fast_handover_rate) — NOT present in this shop's real metric_list",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "snapshot_date + metric_id",
    "CURRENT_PERMISSION": "GRANTED (scope) but metric absent for this shop",
    "REAL_PAYLOAD_PROVEN": "NO (confirmed absent — full 15-metric list captured and checked)",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "MISSING_SOURCE",
    "GAP_ACTION": "Not returned for this shop currently (possibly not applicable to its fulfillment channel) — not fabricated."
  },
  {
    "HH_KPI": "Điểm Sao Quả Tạ",
    "PLATFORM": "SHOPEE",
    "SECTION": "VẬN HÀNH Shopee",
    "OFFICIAL_ENDPOINT": "GET /api/v2/account_health/get_penalty_point_history",
    "API_FIELD": "penalty_point_list (0 rows returned = 0 real current points)",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "snapshot_date",
    "CURRENT_PERMISSION": "GRANTED",
    "REAL_PAYLOAD_PROVEN": "YES (PASS_EMPTY confirmed real; not a permission failure)",
    "CORE_LOCATION": "(not yet loaded into a dedicated table this phase)",
    "MART_LOCATION": "mart.v_ai_operations_daily (via metric_list only)",
    "AI_VIEW": "v_ai_operations_daily",
    "STATUS": "API_ACTUAL",
    "GAP_ACTION": "Endpoint proven live; metric_list snapshot covers the summary view. A dedicated penalty_point_history detail table is a reasonable follow-up if HH wants the itemized log, not built this pass."
  },
  {
    "HH_KPI": "Vi phạm liên quan đến cửa hàng",
    "PLATFORM": "TIKTOK",
    "SECTION": "VẬN HÀNH Tiktok",
    "OFFICIAL_ENDPOINT": "(none found)",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "shop",
    "CURRENT_PERMISSION": "NOT GRANTED (no such scope exists on this app; none found in TikTok Shop's official read-domain set across this project's research)",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NOT_EXPOSED_PUBLIC_API",
    "GAP_ACTION": "No public TikTok Shop API for shop-level violation points was found. Product Information Issue Diagnosis was NOT substituted (not proven equivalent, per explicit instruction)."
  },
  {
    "HH_KPI": "Vi phạm liên quan đến sản phẩm",
    "PLATFORM": "TIKTOK",
    "SECTION": "VẬN HÀNH Tiktok",
    "OFFICIAL_ENDPOINT": "(none found)",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "product",
    "CURRENT_PERMISSION": "NOT GRANTED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NOT_EXPOSED_PUBLIC_API",
    "GAP_ACTION": "Same as above."
  },
  {
    "HH_KPI": "Vi phạm kiểm soát rủi ro",
    "PLATFORM": "TIKTOK",
    "SECTION": "VẬN HÀNH Tiktok",
    "OFFICIAL_ENDPOINT": "(none found)",
    "API_FIELD": "N/A",
    "FORMULA_IF_DERIVED": "",
    "GRAIN": "shop",
    "CURRENT_PERMISSION": "NOT GRANTED",
    "REAL_PAYLOAD_PROVEN": "NO",
    "CORE_LOCATION": "",
    "MART_LOCATION": "",
    "AI_VIEW": "",
    "STATUS": "NOT_EXPOSED_PUBLIC_API",
    "GAP_ACTION": "Same as above."
  }
];
