-- =====================================================================
-- 057_STAGED_tiktok_affiliate_partner_tapshop_columns.sql
-- STATUS: STAGED / NOT APPLIED — pending human approval.
--
-- DEPENDENCY (added 2026-09-21, Phase 6C Task F): the ADD COLUMN below
-- is still independently safe/necessary (additive, no data yet). BUT
-- the backfill statement further down must NOT run using its original
-- single-table form until sql/061 (core.fact_settlement_sku_transaction)
-- exists AND is populated by the updated write path — doing so earlier
-- would silently write undercounted values for any (order_id,sku_id)
-- that hit the multi-transaction collision, creating data that LOOKS
-- populated but is wrong, which is worse than leaving it NULL
-- (MISSING_SOURCE is a safe, honest state; a wrong nonzero is not).
-- Sequence: sql/061 + incr_worker.py write-path deploy -> THEN this
-- file's (updated) backfill statement -> THEN sql/063.
--
-- P8.7 fee standardization — promotes two of the three previously
-- JSONB-only-captured TikTok affiliate/ads fee sub-fields to named,
-- indexed columns, per Section H.2's requirement to "giữ component
-- breakdown" explicitly (not just inside fee_tax_breakdown_raw).
--
-- Full-population reconciliation this session (2026-09-01..09-15, 1105
-- matched orders, 1806 sku rows) proved these are the ONLY remaining
-- unmapped nonzero fee sub-fields — order-level fee_and_tax_amount now
-- reconciles to SUM(all 8 unique components) with a residual of exactly
-- 0 (-61,686,347 == -61,686,347) once these two plus the already-
-- captured affiliate_ads_commission_amount (sql/054) are included.
--
-- Values (VND, this window):
--   affiliate_partner_commission_amount: sum=-341,354 across 23 sku rows
--   tap_shop_ads_commission:             sum=-164,772 across 14 sku rows
--
-- CAPTURE ONLY. Additive. Does not alter fixed_fee/payment_fee/vxp_fee/
-- infrastructure_fee/affiliate_fee or any existing column. Does NOT
-- touch mart.v_ceo_ecom_daily or any CM1/CM2 formula — that wiring (if
-- approved) is a SEPARATE staged change (see
-- 058_STAGED_canonical_fee_components_view.sql and the P8.7 preview
-- report) so the accounting-role decision and the capture decision can
-- be approved independently.
-- =====================================================================
ALTER TABLE core.fact_settlement_sku_fee
    ADD COLUMN IF NOT EXISTS affiliate_partner_commission_amount NUMERIC(18,4),
    ADD COLUMN IF NOT EXISTS tap_shop_ads_commission_amount NUMERIC(18,4);

-- Backfill statement — UPDATED 2026-09-21 (Phase 6C Task C): the
-- statement below (reading fee_tax_breakdown_raw directly off
-- fact_settlement_sku_fee) is STILL CORRECT ONLY for orders that never
-- hit the multi-transaction-per-sku_id collision (see sql/061) — for a
-- collided (order_id, sku_id), fee_tax_breakdown_raw on this table
-- reflects just one surviving entry, understating the true value the
-- same way the pre-fix revenue/shipping totals did. Once sql/061 (the
-- lossless transaction-grain table) exists and is populated, prefer:
--
-- UPDATE core.fact_settlement_sku_fee f
-- SET affiliate_partner_commission_amount = t.partner_sum,
--     tap_shop_ads_commission_amount = t.tapshop_sum
-- FROM (
--     SELECT order_id, sku_id,
--            sum(affiliate_partner_commission_amount) AS partner_sum,
--            sum(tap_shop_ads_commission_amount) AS tapshop_sum
--     FROM core.fact_settlement_sku_transaction
--     WHERE channel='TIKTOK'
--     GROUP BY order_id, sku_id
-- ) t
-- WHERE f.channel='TIKTOK' AND f.order_id=t.order_id AND f.sku_id=t.sku_id;
--
-- The original single-table statement is kept below for reference /
-- for use only if sql/061 is deliberately not adopted:
--
-- UPDATE core.fact_settlement_sku_fee
-- SET affiliate_partner_commission_amount = (fee_tax_breakdown_raw->'fee'->>'affiliate_partner_commission_amount')::numeric,
--     tap_shop_ads_commission_amount = (fee_tax_breakdown_raw->'fee'->>'tap_shop_ads_commission')::numeric
-- WHERE channel='TIKTOK' AND fee_tax_breakdown_raw IS NOT NULL
--   AND (affiliate_partner_commission_amount IS NULL OR tap_shop_ads_commission_amount IS NULL);
--
-- Going-forward capture requires one code change: incr_worker.py's
-- run_finance() INSERT should add these two columns, reading
-- fee_tax.get("affiliate_partner_commission_amount") and
-- fee_tax.get("tap_shop_ads_commission") — same pattern as
-- affiliate_ads_commission_amount added in sql/054.
